from __future__ import annotations

import hashlib
import json
import os
import re
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

import psycopg

from arb_memory.graph import reference_targets, related_artefacts


SLUG_DISALLOWED_RE = re.compile(r"[^A-Za-z0-9._-]")

_ARTEFACT_COLS = (
    "artefact_id",
    "version",
    "content",
    "content_bytes",
    "content_mime",
    "repo_pointer",
    "content_hash",
    "source",
    "author",
    "created_at",
)


@dataclass
class VaultExportSettings:
    dsn: str
    vault_root: str
    similarity_threshold: float = 0.35


def resolve_settings(env) -> VaultExportSettings:
    return VaultExportSettings(
        dsn=env["ARB_VAULT_EXPORT_DSN"],
        vault_root=env["ARB_VAULT_EXPORT_ROOT"],
        similarity_threshold=float(env.get("ARB_VAULT_EXPORT_SIMILARITY_THRESHOLD", "0.35")),
    )


def _slug(artefact_id: str) -> str:
    return SLUG_DISALLOWED_RE.sub("", artefact_id)


def _idhash(artefact_id: str) -> str:
    return hashlib.sha256(artefact_id.encode("utf-8")).hexdigest()[:8]


def _filename(artefact_id: str) -> str:
    return f"{_slug(artefact_id)}-{_idhash(artefact_id)}.md"


FOOTER_MARKER = (
    "<!-- generated by vault_export: graph footer — do not edit; regenerated nightly -->"
)


def _stem(artefact_id: str) -> str:
    return _filename(artefact_id)[: -len(".md")]


def _footer(references: list[str], related: list[tuple[str, int, float]]) -> str:
    if not references and not related:
        return ""
    lines = ["", FOOTER_MARKER, ""]
    if references:
        lines.append("## References")
        lines.extend(f"- [[{_stem(t)}|{t}]]" for t in references)
        lines.append("")
    if related:
        lines.append("## Related")
        lines.extend(f"- [[{_stem(t)}|{t}]] (distance {d:.2f})" for t, _v, d in related)
        lines.append("")
    return "\n".join(lines)


def _latest_artefacts(conn) -> list[dict]:
    rows = conn.execute(
        f"""
        SELECT DISTINCT ON (artefact_id) {", ".join(_ARTEFACT_COLS)}
        FROM artefacts
        ORDER BY artefact_id, version DESC
        """
    ).fetchall()
    return [dict(zip(_ARTEFACT_COLS, row)) for row in rows]


def _linked_tags(conn, artefact_id: str, version: int) -> list[str]:
    # No ORDER BY: tags are unioned into a set and sorted below, so row order from
    # Postgres is irrelevant here (unlike an earlier design iteration that also picked a
    # "first hint wins" description field by lowest id -- that field was dropped to match
    # the panel-approved frontmatter list, and this query no longer needs a tie-break).
    rows = conn.execute(
        """
        SELECT metadata
        FROM hints
        WHERE artefact_id = %s AND artefact_version = %s AND deleted_at IS NULL
        """,
        (artefact_id, version),
    ).fetchall()
    tags: set[str] = set()
    for (metadata,) in rows:
        tags.update(metadata.get("tags", []) or [])
    return sorted(tags)


def _frontmatter(artefact: dict, tags: list[str], exported_at: str) -> str:
    # json.dumps() for every caller-influenced string field: artefact_id/source/author are
    # caller-chosen strings with no format validation (store.py's write path enforces none),
    # and tags come from hint metadata a caller also controls. A YAML-hostile value (a colon
    # followed by a space, a "#", an embedded quote) in an unquoted or naively-quoted field
    # would either break frontmatter parsers or silently truncate the value. JSON string/array
    # syntax is valid YAML flow syntax, so this is also valid frontmatter.
    lines = [
        "---",
        f"artefact_id: {json.dumps(artefact['artefact_id'])}",
        f"aliases: [{json.dumps(artefact['artefact_id'])}]",
        f"version: {artefact['version']}",
        f"source: {json.dumps(artefact['source'])}",
        f"author: {json.dumps(artefact['author'])}",
        f"created_at: {artefact['created_at'].isoformat()}",
        f"content_hash: {json.dumps(artefact['content_hash'])}",
        f"tags: {json.dumps(tags)}",
        f"exported_at: {exported_at}",
        "---",
        "",
    ]
    return "\n".join(lines)


def _body(artefact: dict) -> str:
    if artefact["content"] is not None:
        return artefact["content"]
    content_bytes = artefact["content_bytes"] or b""
    return (
        f"_binary artefact, content_mime: {artefact['content_mime']}, "
        f"{len(content_bytes)} bytes — not rendered_\n"
    )


def export_vault(conn, vault_root: str, *, similarity_threshold: float = 0.35, related_k: int = 5) -> dict:
    root = Path(vault_root)
    root.mkdir(parents=True, exist_ok=True)
    exported_at = datetime.now(timezone.utc).isoformat()

    artefacts = _latest_artefacts(conn)
    seen_hashes: dict[str, str] = {}
    for artefact in artefacts:
        artefact_id = artefact["artefact_id"]
        idhash = _idhash(artefact_id)
        if idhash in seen_hashes and seen_hashes[idhash] != artefact_id:
            raise RuntimeError(
                f"idhash collision: {artefact_id!r} and {seen_hashes[idhash]!r} "
                f"both hash to {idhash!r}"
            )
        seen_hashes[idhash] = artefact_id
    export_ids = set(seen_hashes.values())

    written = 0
    for artefact in artefacts:
        artefact_id = artefact["artefact_id"]
        tags = _linked_tags(conn, artefact_id, artefact["version"])
        body = _body(artefact)
        references = reference_targets(body, artefact_id, export_ids)
        related = related_artefacts(
            conn, artefact_id, artefact["version"], k=related_k, threshold=similarity_threshold,
            subject_hints="live",
        )
        footer = _footer(references, related)
        if footer and not body.endswith("\n"):
            # _footer's leading empty line supplies ONE newline; a body that doesn't end
            # with its own newline needs a second so the marker is preceded by a true
            # BLANK line, not just a line break (round-1 panel finding, all three seats).
            footer = "\n" + footer
        text = _frontmatter(artefact, tags, exported_at) + body + footer
        (root / _filename(artefact_id)).write_text(text, encoding="utf-8")
        written += 1

    return {"written": written}


def main() -> int:
    settings = resolve_settings(os.environ)
    with psycopg.connect(settings.dsn) as conn:
        result = export_vault(conn, settings.vault_root, similarity_threshold=settings.similarity_threshold)
    print(f"vault export complete: {result['written']} artefacts written to {settings.vault_root}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
