#!/usr/bin/env python3
"""Shared helpers for the docs index scripts.

`docs/index.json` is parsed with the stdlib json module. The file must contain
a JSON array of objects.
"""

from __future__ import annotations

import json
import subprocess
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
INDEX_PATH = ROOT / "docs" / "index.json"
INDEX_MD_PATH = ROOT / "docs" / "INDEX.md"

VALID_STATUSES = {"current", "design", "runbook", "archive", "incident"}
VALID_AUDIENCES = {"worker", "orchestrator", "operator", "any"}
COLLECTION_EXEMPTIONS = {
    "docs/reviews": "docs/reviews",
    "docs/superpowers/reviews": "docs/superpowers/reviews",
    "docs/superpowers/plans": "docs/superpowers/plans",
    "docs/superpowers/specs": "docs/superpowers/specs",
}


def repo_rel(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def load_entries() -> list[dict[str, str]]:
    try:
        data = json.loads(INDEX_PATH.read_text())
    except json.JSONDecodeError as exc:
        raise ValueError(f"{repo_rel(INDEX_PATH)} must be valid JSON: {exc}") from exc
    if not isinstance(data, list):
        raise ValueError(f"{repo_rel(INDEX_PATH)} must contain a top-level list")
    return data


def render_index(entries: list[dict[str, str]]) -> str:
    grouped: dict[str, list[dict[str, str]]] = {
        status: [] for status in ["current", "runbook", "design", "incident", "archive"]
    }
    for entry in sorted(entries, key=lambda item: item["path"]):
        grouped.setdefault(entry["status"], []).append(entry)

    lines = [
        "# Documentation Index",
        "",
        "<!-- Generated by scripts/gen-doc-index from docs/index.json. Do not edit by hand. -->",
        "",
        "This index is the routing layer for agents and humans. Operational lessons that",
        "another seat would need during an incident go in `docs/runbooks/` as symptom-named",
        "runbooks; provenance and release history stay in `CHANGELOG.md`.",
        "",
    ]
    for status, rows in grouped.items():
        if not rows:
            continue
        lines.extend(
            [
                f"## {status.title()}",
                "",
                "| Path | Audience | Purpose |",
                "|---|---|---|",
            ]
        )
        for entry in rows:
            path = entry["path"]
            lines.append(f"| `{path}` | `{entry['audience']}` | {entry['purpose']} |")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def tracked_markdown_paths() -> set[str]:
    proc = subprocess.run(
        ["git", "ls-files", "*.md"],
        cwd=ROOT,
        check=True,
        text=True,
        capture_output=True,
    )
    paths = set()
    for line in proc.stdout.splitlines():
        # A symlinked markdown file (e.g. GEMINI.md -> AGENTS.md) is an alias, not an
        # independent document — it must not demand its own docs/index.json entry.
        if (ROOT / line).is_symlink():
            continue
        if line in {"docs/fragments/agents-base.md", "docs/fragments/coding.md"}:
            paths.add(line)
            continue
        if line.startswith("docs/") or "/" not in line:
            paths.add(line)
    return paths


def is_collection_exempt(path: str, indexed_paths: set[str]) -> bool:
    for prefix, collection_path in COLLECTION_EXEMPTIONS.items():
        if path.startswith(prefix + "/") and collection_path in indexed_paths:
            return True
    return False


def validate_entries(entries: list[dict[str, str]]) -> list[str]:
    errors: list[str] = []
    indexed_paths: set[str] = set()

    for i, entry in enumerate(entries, start=1):
        if not isinstance(entry, dict):
            errors.append(f"entry {i}: expected object")
            continue
        required = {"path", "purpose", "status", "audience"}
        missing = required - set(entry)
        extra = set(entry) - required
        if missing:
            errors.append(f"entry {i}: missing fields {sorted(missing)}")
        if extra:
            errors.append(f"entry {i}: unknown fields {sorted(extra)}")
        if missing:
            continue

        path = entry["path"]
        purpose = entry["purpose"]
        status = entry["status"]
        audience = entry["audience"]
        if path in indexed_paths:
            errors.append(f"{path}: duplicate index entry")
        indexed_paths.add(path)
        if status not in VALID_STATUSES:
            errors.append(f"{path}: invalid status {status!r}")
        if audience not in VALID_AUDIENCES:
            errors.append(f"{path}: invalid audience {audience!r}")
        if "\n" in purpose or "\r" in purpose:
            errors.append(f"{path}: purpose must be a single line")
        if len(purpose) > 120:
            errors.append(f"{path}: purpose exceeds 120 chars")
        if not (ROOT / path).exists():
            errors.append(f"{path}: indexed path does not exist")

    tracked = tracked_markdown_paths()
    for path in sorted(tracked):
        if path in indexed_paths:
            continue
        if is_collection_exempt(path, indexed_paths):
            continue
        errors.append(f"{path}: tracked markdown missing from docs/index.json")

    stale_expected = render_index(entries)
    if INDEX_MD_PATH.exists():
        actual = INDEX_MD_PATH.read_text()
        if actual != stale_expected:
            errors.append("docs/INDEX.md is stale; run scripts/gen-doc-index")
    else:
        errors.append("docs/INDEX.md is missing; run scripts/gen-doc-index")

    return errors
