"""Inject-revert proofs for claim_admissibility_v.

`admissible` = confirmed_now AND attested. A conjunction hides which half failed, so a
truth-table test asserting only `admissible is False` would stay green with either half
permanently false. These assert each half moves independently.

INJECT-REVERT RESULTS - observed pytest output, PostgreSQL 17.10.

Each injection is a temporary edit to the named source file, run against the live dev DSN,
then reverted with `git checkout --`; the sweep asserts a CLEAN tree at the end. Tests are
cited by NAME, never by line number: an earlier revision of this record cited :170 and :212,
which had drifted to :228 and :297 by the time anyone read them, and quoted a baseline of
"30 passed" that a later commit had made false. A record that rots silently is worse than no
record, because it is still believed.

--- Round 1 (2026-07-26), command: pytest test_gate_schema.py test_gate_schema_deny_proof.py

Baseline at that commit: 30 passed — STALE as of the round-3 sweep below, and deliberately
kept. DO NOT DELETE THESE AS CRUFT. This record is append-only for the same reason panel votes
are: a superseded measurement is still a measurement, and these three outputs were observed
against that baseline. Scoping them to the round that produced them keeps them true; deleting
them would destroy the only evidence that the three original view predicates were ever
proven falsifiable, and re-deriving would not restore the provenance. Supersede by ADDING a
round, never by editing or removing an earlier one.

1. In `attested`, `a.verifier_family <> c.author_family` -> `true` (F1 collapses):

    FAILED test_gate_schema.py::test_same_family_attestation_is_not_an_attestation_at_all
    1 failed, 29 passed in 7.18s
    E         At index 0 diff: True != False

2. In `decorrelation_provenance`, delete `WHEN count(*) = 0 THEN 'none'`:

    FAILED test_gate_schema.py::test_no_attestation_reads_not_attested_and_provenance_none
    FAILED test_gate_schema.py::test_same_family_attestation_is_not_an_attestation_at_all
    FAILED test_gate_schema.py::test_incomplete_cross_family_attestation_is_never_wire
    FAILED test_gate_schema_deny_proof.py::test_provenance_is_not_hardwired_to_a_single_value
    FAILED test_gate_schema_deny_proof.py::test_no_attestation_reads_none_never_degraded
    5 failed, 25 passed in 9.52s
    E       AssertionError: assert 'degraded' == 'none'

    Broader than the single predicted failure, which is stronger, not weaker: bool_and over
    zero rows really does return NULL and really does fall through to 'degraded'.

3. In `decorrelation_provenance`, delete the three `<> ''` completeness predicates, leaving
   `attested`'s intact (the population drift the spec says already happened once):

    FAILED test_gate_schema.py::test_incomplete_cross_family_attestation_is_never_wire
    1 failed, 29 passed in 7.21s
    E       AssertionError: provenance subquery counted a row `attested` rejected - the two
            WHERE clauses drifted / assert 'wire' != 'wire'

--- Round 3 (2026-07-26), full sweep — REGENERATED by the committed harness.

Produced by `scripts/mutation_sweep.py`, not by hand, so it is reproducible rather than
re-derivable. Spec: `tests/arb_memory/gate_mutation_sweep.json` (8 mutations). Command:

    set -a; . /Users/<user>/<workspace>/envs/arb-memory-dev.env; set +a
    .venv/bin/python scripts/mutation_sweep.py \
        --spec tests/arb_memory/gate_mutation_sweep.json \
        --test-cmd ".venv/bin/python -m pytest tests/arb_memory/test_gate_schema.py \
            tests/arb_memory/test_gate_grants.py tests/arb_memory/test_gate_store.py \
            tests/arb_memory/test_gate_schema_deny_proof.py -q"

Every mutation below is one the suite ONCE FAILED TO CATCH. M1/M2 and M5 were the r2 panel's
P1s; M4 was codex-sol's P2. Before their fixes each left the suite fully green.

The harness refuses to run on a dirty tree and refuses a baseline that collects zero tests,
so this report cannot be the output of a sweep that silently mutated nothing or reverted over
uncommitted work — both of which happened during the hand-run version of this sweep.

    BASELINE (no mutation): 45 passed in 11.75s

    M1  seat_posture_v -> constant false (fail-open: every seat un-gated, spec §3)
        2 failed, 43 passed in 11.88s
        FAILED tests/arb_memory/test_gate_grants.py::test_gate_reader_cannot_mint_through_an_ambient_public_grant
        FAILED tests/arb_memory/test_gate_schema.py::test_seat_posture_v_projects_both_postures

    M2  lease_lane_v -> constant 'exempt' (fail-open: total lane bypass, spec §5.3)
        2 failed, 43 passed in 11.85s
        FAILED tests/arb_memory/test_gate_grants.py::test_gate_reader_cannot_mint_through_an_ambient_public_grant
        FAILED tests/arb_memory/test_gate_schema.py::test_lease_lane_v_projects_both_lanes

    M3  expiry operator  >  ->  >=
        1 failed, 44 passed in 11.61s
        FAILED tests/arb_memory/test_gate_schema.py::test_review_by_exactly_at_now_is_expired_not_confirmed

    M4  raw status/review_by hardwired in claim_admissibility_v
        1 failed, 44 passed in 11.57s
        FAILED tests/arb_memory/test_gate_schema.py::test_claim_admissibility_v_projects_the_raw_claim_columns

    M5  PUBLIC view revoke narrowed  REVOKE ALL -> REVOKE INSERT
        1 failed, 44 passed in 11.63s
        FAILED tests/arb_memory/test_gate_grants.py::test_gate_reader_cannot_mint_through_an_ambient_public_grant

    M6  assert_gate_role_isolation() call removed from apply_gate_reader_grants
        2 failed, 43 passed in 12.19s
        FAILED tests/arb_memory/test_gate_grants.py::test_isolation_assertion_refuses_a_role_owning_a_gate_relation
        FAILED tests/arb_memory/test_gate_grants.py::test_isolation_assertion_refuses_a_role_with_a_membership

    M7  re-run FOREIGN KEY dropped
        1 failed, 44 passed in 11.90s
        FAILED tests/arb_memory/test_gate_schema.py::test_attestation_cannot_cite_a_nonexistent_rerun_artefact

    M8  CHECK on attestations.falsifier_kind dropped
        1 failed, 44 passed in 11.68s
        FAILED tests/arb_memory/test_gate_schema.py::test_attestation_check_constraints_reject_out_of_domain_values[falsifier_kind-interpretive-dance]

    RESTORED BASELINE: 45 passed in 11.83s
    tree after sweep: CLEAN

Note on M1/M2: they also fail the ambient-grant deny-proof for a second, independent reason —
a view whose column is a constant is no longer a SIMPLE view, so it stops being automatically
updatable and the INSERT raises ObjectNotInPrerequisiteState instead of the expected
InsufficientPrivilege. Defence in depth, but the projection tests are the intended catcher.

To re-run after changing the gate surface: add the mutation to the spec JSON and run the
command above. A mutation that survives prints "*** NO TEST FAILED - MUTATION SURVIVES ***"
and the harness exits 1.
"""

import os

import pytest

psycopg = pytest.importorskip("psycopg")
pytest.importorskip("pgvector")
pytestmark = pytest.mark.skipif(not os.environ.get("ARB_MEMORY_DSN"), reason="no ARB_MEMORY_DSN")

from tests.arb_memory.test_gate_schema import _attest, _claim, _row  # noqa: E402


def test_each_half_of_admissible_moves_independently(scratch):
    """If either column is hardwired, one of these four rows is wrong."""
    _claim(scratch, "c-tt", status="confirmed")
    _attest(scratch, "c-tt")
    assert _row(scratch, "c-tt")[:2] == (True, True)

    _claim(scratch, "c-tf", status="confirmed")
    assert _row(scratch, "c-tf")[:2] == (True, False)

    _claim(scratch, "c-ft", status="unconfirmed")
    _attest(scratch, "c-ft")
    assert _row(scratch, "c-ft")[:2] == (False, True)

    _claim(scratch, "c-ff", status="unconfirmed")
    assert _row(scratch, "c-ff")[:2] == (False, False)


def test_provenance_is_not_hardwired_to_a_single_value(scratch):
    """Guards the count(*)=0-first ordering: if the CASE collapsed, all three read alike."""
    _claim(scratch, "c-none", author_provenance="wire")
    _claim(scratch, "c-wire", author_provenance="wire")
    _attest(scratch, "c-wire", provenance="wire")
    _claim(scratch, "c-deg", author_provenance="configured")
    _attest(scratch, "c-deg", provenance="wire")

    observed = {_row(scratch, cid)[2] for cid in ("c-none", "c-wire", "c-deg")}
    assert observed == {"none", "wire", "degraded"}, (
        f"provenance CASE collapsed - observed only {observed}"
    )


def test_no_attestation_reads_none_never_degraded(scratch):
    """bool_and over zero rows is NULL. If count(*)=0 stopped being tested first, a claim with
    NO attestation would report as merely weakly-decorrelated."""
    _claim(scratch, "c-empty")
    assert _row(scratch, "c-empty")[2] == "none"
